#!/bin/sh
# Regenerates requirements.lock (review FR-001): every Python package the
# router installs, pinned to an exact version with the sha256 of each of
# its release files, for FR_OS's target -- Debian bookworm, Python 3.11,
# x86_64. The image build and the updater install with --require-hashes,
# so a dependency can only change through a reviewed change to this file,
# which then travels inside the signed release tarball.
#
# Pin what the tests ran against: pass a `pip freeze` of the tested
# environment as $1 (the default resolves to the newest compatible
# versions). Needs uv (https://docs.astral.sh/uv/).
set -eu
cd "$(dirname "$0")/.."
constraints=${1:-}
build_in=$(mktemp)
trap 'rm -f "$build_in"' EXIT
# The build backend, installed from the lock too: the release is then
# built with --no-build-isolation, so pip fetches nothing unpinned.
printf 'setuptools==68.1.2\nwheel==0.42.0\n' > "$build_in"
uv pip compile pyproject.toml "$build_in" --extra webui --generate-hashes \
    --python-version 3.11 --python-platform x86_64-manylinux_2_36 \
    ${constraints:+-c "$constraints"} --no-header --no-annotate -o requirements.lock.tmp
{
    echo "# Generated by scripts/lock-requirements.sh -- do not edit by hand."
    echo "# Installed with pip --require-hashes by the image build and the updater (review FR-001)."
    cat requirements.lock.tmp
} > requirements.lock
rm -f requirements.lock.tmp
